### PR TITLE
YUNIKORN-38. YuniKorn UI behaves incorrectly when max resource is not set

### PR DESCRIPTION
**Pull request by akhilpb001**
Yunikorn JIRA: https://issues.apache.org/jira/browse/YUNIKORN-38

### CODE REVIEW

**Comment by akhilpb001** [comment]
@yangwwei @sunilgovind @wilfred-s  please review the PR

**Comment by yangwwei** [comment]
Hi @akhilpb001 

Thanks for working on this!! I tested the changes locally and attached the screenshot here, there are 2 things I want to discuss

YuniKorn_UI

1. for the logo, can you please use the logos we have here: https://github.com/apache/incubator-yunikorn-core/tree/master/docs/images/logo. Since the background is dark blue, I think we can try the gray one.
2. for the usage bar, now it is nicer, but are they static values? Can we calculate the relative percentage to the biggest queue-usage and use that for the usage-bar?

**Comment by akhilpb001** [comment]
@yangwwei 
1. Will use the new logo
2. I took the value from response. I thought they are calculated by scheduler itself.  How do you want me to calculate this? I did not understand what you said above.

**Comment by akhilpb001** [comment]
@yangwwei 
1. I have updated the PR with the new logo for side nav bar
2. I think it would be better the scheduler to send the absUsedCapacity in the api response (which is used to show usage bar), because sometimes configured capacity could be empty and UI can not do that calculation in that case.

**Comment by yangwwei** [comment]
Great, looks good to me. +1

**Pull request merged**
